# Generated by Django 5.1.3 on 2024-11-09 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('outer', '아우터'), ('top', '상의'), ('bottom', '하의'), ('other', '기타')], max_length=10)),
                ('warmth_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')])),
                ('is_frequent', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('temperature_feedback', models.JSONField(default=dict)),
                ('condition_preference', models.CharField(default='normal', max_length=20)),
                ('avoid_categories', models.ManyToManyField(related_name='avoided_outfits', to='weather.outfit')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('special_conditions', models.CharField(blank=True, max_length=50)),
                ('feedback', models.CharField(blank=True, max_length=20)),
                ('user_outfit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.outfit')),
            ],
        ),
    ]
